const input = document.querySelector("#input")
const select = document.querySelector("#select")
const text = document.querySelector("#text")
const submit = document.querySelector("#submit")
const ul = document.querySelector()